version: 2.1

orbs: 
  docker: circleci/docker@2.0.1

workflows:
  build-workflow:
    jobs:
      - build-and-push:
          context:
            - dockerhub

jobs:
  build-and-push:
    steps:
      - docker/publish:
          image: thinxcloud/couchdb
          update-description: true